spring:
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driverClassName: ${datasource_driver}

  sql:
    init:
      mode: never

jwt:
  key: ${jwt_key}