spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/coding-dashboad?sslMode=VERIFY_IDENTITY
    username: ${datasource_username}
    password: ${datasource_password}


  sql:
    init:
      mode: never