spring:
  datasource:
    url: jdbc:h2:mem:coding_dashboard
    username: admin
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

jwt:
  key: thisIsKeyIsOnlyForTesting123456789000000000000000000000000000000